# SETUP ANALYSIS

SETUP_HIP_KNEE_ANKLE_ANGLES_LOW = 15
SETUP_HIP_KNEE_ANKLE_ANGLES_MEDIUM = 25
SETUP_HIP_KNEE_ANKLE_ANGLES_HIGH = 35

SETUP_HIP_VERT_BALL_HIP_DIST_LOW = 0.15
SETUP_HIP_VERT_BALL_HIP_DIST_MEDIUM = 0.25
SETUP_HIP_VERT_BALL_HIP_DIST_HIGH = 0.35

SETUP_HIP_HORIZ_BALL_HIP_DIST_LOW = 0.15
SETUP_HIP_HORIZ_BALL_HIP_DIST_MEDIUM = 0.25
SETUP_HIP_HORIZ_BALL_HIP_DIST_HIGH = 0.35

SETUP_STANCE_WIDTH_DIST_LOW = 0.15
SETUP_STANCE_WIDTH_DIST_MEDIUM = 0.25
SETUP_STANCE_WIDTH_DIST_HIGH = 0.35

SETUP_TILT_DIFF_LOW = 10
SETUP_TILT_DIFF_MEDIUM = 15
SETUP_TILT_DIFF_HIGH = 20

# LOAD ANALYSIS

LOADING_ASYM_LOW = 10
LOADING_ASYM_MEDIUM = 20
LOADING_ASYM_HIGH = 30

LOADING_DEPTH_DIFF_LOW = 20
LOADING_DEPTH_DIFF_MEDIUM = 30
LOADING_DEPTH_DIFF_HIGH = 40

LOADING_MAX_TIMING_DIFF_LOW = 0.2
LOADING_MAX_TIMING_DIFF_MEDIUM = 0.4
LOADING_MAX_TIMING_DIFF_HIGH = 0.6

LOADING_TIME_TO_TRANS_LOW = 0.3
LOADING_TIME_TO_TRANS_MEDIUM = 0.5
LOADING_TIME_TO_TRANS_HIGH = 0.8

# RISING ANALYSIS

RISING_JUMP_HEIGHT_DIFF_LOW = 0.03
RISING_JUMP_HEIGHT_DIFF_MEDIUM = 0.05
RISING_JUMP_HEIGHT_DIFF_HIGH = 0.08

RISING_BALL_HEIGHT_DIFF_LOW = 0.05
RISING_BALL_HEIGHT_DIFF_MEDIUM = 0.1
RISING_BALL_HEIGHT_DIFF_HIGH = 0.15

RISING_BALL_HORIZ_DIFF_LOW = 0.05
RISING_BALL_HORIZ_DIFF_MEDIUM = 0.1
RISING_BALL_HORIZ_DIFF_HIGH = 0.15

WINDUP_DIFF_LOW = 0.3
WINDUP_DIFF_MEDIUM = 0.5
WINDUP_DIFF_HIGH = 0.8

WINDUP_CURVATURE_DIFF_LOW = 0.002
WINDUP_CURVATURE_DIFF_MEDIUM = 0.005
WINDUP_CURVATURE_DIFF_HIGH = 0.01

WINDUP_PATH_LENGTH_DIFF_LOW = 0.02
WINDUP_PATH_LENGTH_DIFF_MEDIUM = 0.05
WINDUP_PATH_LENGTH_DIFF_HIGH = 0.1

MAX_TIMING_DIFF_LOW = 0.2
MAX_TIMING_DIFF_MEDIUM = 0.4
MAX_TIMING_DIFF_HIGH = 0.6

DIP_SHOULDER_ELBOW_WRIST_LOW = 10
DIP_SHOULDER_ELBOW_WRIST_MEDIUM = 20
DIP_SHOULDER_ELBOW_WRIST_HIGH = 30

DIP_ARM_TORSO_ANGLE_LOW = 10
DIP_ARM_TORSO_ANGLE_MEDIUM = 20
DIP_ARM_TORSO_ANGLE_HIGH = 30

SETUP_POINT_SHOULDER_ELBOW_WRIST_LOW = 10
SETUP_POINT_SHOULDER_ELBOW_WRIST_MEDIUM = 20
SETUP_POINT_SHOULDER_ELBOW_WRIST_HIGH = 30

SETUP_POINT_ARM_TORSO_ANGLE_LOW = 10
SETUP_POINT_ARM_TORSO_ANGLE_MEDIUM = 20
SETUP_POINT_ARM_TORSO_ANGLE_HIGH = 30

SETUP_POINT_BALL_EYE_DIFF_X_LOW = 0.05
SETUP_POINT_BALL_EYE_DIFF_X_MEDIUM = 0.1
SETUP_POINT_BALL_EYE_DIFF_X_HIGH = 0.15

SETUP_POINT_BALL_EYE_DIFF_Y_LOW = 0.05
SETUP_POINT_BALL_EYE_DIFF_Y_MEDIUM = 0.1
SETUP_POINT_BALL_EYE_DIFF_Y_HIGH = 0.15

# RELEASE ANALYSIS

RELEASE_TIMING_DIFF_LOW = 0.2
RELEASE_TIMING_DIFF_MEDIUM = 0.4
RELEASE_TIMING_DIFF_HIGH = 0.6

RELEASE_TILT_DIFF_LOW = 15
RELEASE_TILT_DIFF_MEDIUM = 25
RELEASE_TILT_DIFF_HIGH = 35

RELEASE_THIGH_DIFF_LOW = 15
RELEASE_THIGH_DIFF_MEDIUM = 25
RELEASE_THIGH_DIFF_HIGH = 35

RELEASE_LEG_DIFF_LOW = 15
RELEASE_LEG_DIFF_MEDIUM = 25
RELEASE_LEG_DIFF_HIGH = 35

RELEASE_SHOULDER_ELBOW_WRIST_LOW = 15
RELEASE_SHOULDER_ELBOW_WRIST_MEDIUM = 25
RELEASE_SHOULDER_ELBOW_WRIST_HIGH = 35

RELEASE_WRIST_SHOULDER_HIP_LOW = 15
RELEASE_WRIST_SHOULDER_HIP_MEDIUM = 25
RELEASE_WRIST_SHOULDER_HIP_HIGH = 35

RELEASE_TORSO_LOW = 15
RELEASE_TORSO_MEDIUM = 25
RELEASE_TORSO_HIGH = 35

RELEASE_BALL_X_DIFF_LOW = 0.15
RELEASE_BALL_X_DIFF_MEDIUM = 0.25
RELEASE_BALL_X_DIFF_HIGH = 0.35

RELEASE_BALL_Y_DIFF_LOW = 0.15
RELEASE_BALL_Y_DIFF_MEDIUM = 0.25
RELEASE_BALL_Y_DIFF_HIGH = 0.35

RELEASE_BALL_MAGNITUDE_LOW = 0.02
RELEASE_BALL_MAGNITUDE_MEDIUM = 0.05
RELEASE_BALL_MAGNITUDE_HIGH = 0.1

RELEASE_BALL_ANGLE_LOW = 10
RELEASE_BALL_ANGLE_MEDIUM = 20
RELEASE_BALL_ANGLE_HIGH = 30

# FOLLOW-THROUGH ANALYSIS

STABLE_DIFF_LOW = 0.1
STABLE_DIFF_MEDIUM = 0.2
STABLE_DIFF_HIGH = 0.4

ARM_STABLE_DIFF_LOW = 0.1
ARM_STABLE_DIFF_MEDIUM = 0.2
ARM_STABLE_DIFF_HIGH = 0.4

OTHER_STABLE_DIFF_LOW = 0.1
OTHER_STABLE_DIFF_MEDIUM = 0.2
OTHER_STABLE_DIFF_HIGH = 0.4

MAX_ELBOW_ANGLE_DIFF_LOW = 5
MAX_ELBOW_ANGLE_DIFF_MEDIUM = 10
MAX_ELBOW_ANGLE_DIFF_HIGH = 20

MAX_ELBOW_ANGLE_STD_LOW = 2
MAX_ELBOW_ANGLE_STD_MEDIUM = 5
MAX_ELBOW_ANGLE_STD_HIGH = 10

ELBOW_STD_DIFF_LOW = 2
ELBOW_STD_DIFF_MEDIUM = 5
ELBOW_STD_DIFF_HIGH = 10

SHOULDER_STD_DIFF_LOW = 2
SHOULDER_STD_DIFF_MEDIUM = 5
SHOULDER_STD_DIFF_HIGH = 10

# LANDING ANALYSIS

LANDING_TORSO_ANGLE_LOW = 10
LANDING_TORSO_ANGLE_MEDIUM = 20
LANDING_TORSO_ANGLE_HIGH = 40
